### ISSUE TITLE
failed to login wetty:ssh in kubernetes

### ISSUE THREAD

**Issue by liuhuiping2013** [butlerx/wetty#254]
**Describe the bug**
deploy in kubernetes, login failed

**To Reproduce**
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wetty
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: wetty
        image: butlerx/wetty
        imagePullPolicy: IfNotPresent
        tty: true
        ports:
          - containerPort: 3000
      - name: wetty-ssh
        image: butlerx/wetty:ssh
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 22
```

**Expected behavior**
login success

**Screenshots**
![Snipaste_2020-07-01_15-19-02](https://user-images.githubusercontent.com/10127284/86214834-497f3b00-bbae-11ea-8ce2-cea57956157c.png)
