### ISSUE TITLE
getaddrinfo wetty-ssh: Name does not resolve

### ISSUE THREAD

**Issue by cyr-ius** [butlerx/wetty#369]
**Describe the bug**
I just updated the container from the docker hub and I come across this issue.
It was working great before the update.
```
wetty    | yarn run v1.22.15
wetty    | $ ssh-keyscan -H wetty-ssh >> ~/.ssh/known_hosts; yarn start --base=/ --ssh-host=hector2.ipocus.net
wetty    | getaddrinfo wetty-ssh: Name does not resolve
wetty    | getaddrinfo wetty-ssh: Name does not resolve
wetty    | getaddrinfo wetty-ssh: Name does not resolve
wetty    | getaddrinfo wetty-ssh: Name does not resolve
wetty    | getaddrinfo wetty-ssh: Name does not resolve
wetty    | $ NODE_ENV=production node . --base=/ --ssh-host=hector2.ipocus.net
wetty    | {"port":3000,"base":"/","title":"WeTTY - The Web Terminal Emulator","level":"info","message":"Starting server","label":"Wetty","timestamp":"2021-12-10T17:38:20.805Z"}
```

My docker-compose
```yaml
services:
  wetty:
    image: wettyoss/wetty
    container_name: wetty
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro     
    environment:
      - TZ=Europe/Paris      
    command:
      - --base=/
      - --ssh-host=hector2.ipocus.net 
```

**Comment by butlerx** [comment]
hmm the default entry-point is designed for use with the wetty-ssh container which is required. this should probably be removed and moved into the docker-compose. 

until then to work around the issue you can set the following 
```yaml
services:
  wetty:
    entrypoint: "yarn start"
```
