### ISSUE TITLE
wetty docker container login

### ISSUE THREAD

**Issue by planetacomputer** [butlerx/wetty#389]
**Describe the bug**
I cannot login in the web console

**To Reproduce**
1. docker run --rm -p 3000:3000 wettyoss/wetty --ssh-host=127.0.0.1
2. 127.0.0.1:3000/wetty
No idea user /password
I also tried:
run --rm -p 3000:3000 wettyoss/wetty --ssh-host=localhost --ssh-user=john --ssh-pass=john
But that user/passw is not accepted.

How to login?

**Comment by butlerx** [comment]
You won't be able to use localhost with docker as that will point to the container itself, You'll need to use the IP of the host machine on the docker network.

**Comment by nogo10** [comment]
Same problem different parameters :  I get the logging screen (not secured https doesn't work) rejects my normally working SSH login name giving me  an ```connection closed by remote host``` error

```
Version:  '2'                                
                                             
services:                                    
                                             
 proxy:                                      
    image: jwilder/nginx-proxy               
    container_name: proxy                    
    restart: unless-stopped                  
    labels:                                  
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"               
    volumes:                                 
      - /var/run/docker.sock:/tmp/docker.sock:ro                                          
      - certs:/etc/nginx/certs:rw            
      - vhost.d:/etc/nginx/vhost.d           
      - html:/usr/share/nginx/html           
      - ./uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro                            
    ports:                                   
      - "80:80"                              
      - "443:443"                            
      - "3000:3000"                          
    networks:                                
      - "default"                            
      - "proxy-tier"

 proxy-letsencrypt:                          
    image: jrcs/letsencrypt-nginx-proxy-companion                                         
    container_name: letsencrypt              
    restart: unless-stopped                  
    environment:                             
      - NGINX_PROXY_CONTAINER=proxy          
    volumes:                                 
      - /var/run/docker.sock:/var/run/docker.sock:ro                                      
    volumes_from:                            
      - "proxy"                              
    depends_on:                              
      - "proxy"                              
    networks:                                
      - "default"                            
      - "proxy-tier"                         
                                             
 portainer:                                  
    image: portainer/portainer               
    container_name: portainer                
    restart: always                          
    environment:                             
      - VIRTUAL_HOST=docker.xxxxx.com 
      - LETSENCRYPT_HOST=docker.xxxxx.com
      - [LETSENCRYPT_EMAIL=info@xxxxx.com](mailto:LETSENCRYPT_EMAIL=info@xxxxx.com)    
    volumes:                                 
      - ./portainer/:/data                   
      - /var/run/docker.sock:/var/run/docker.
sock
ports:                                   
      - "9000:9000"                          
                                             
 wetty:                                      
    # built from Dockerfile                  
    image: butlerx/wetty                     
#    command: docker run --rm -p 3000:3000  -
-ssh-user "john"                             
    restart: always                          
    mem_limit: 300M                          
    container_name: wetty                    
#    tty: true                               
#    env_file:                               
#     - env-wetty                            
    environment:                             
      SSHHOST: 'wetty'                       
      SSHPORT: 3000                          
      NODE_ENV: 'production'                 
    volumes:                                 
#     - wetty-data:/home/node                
      - /etc/localtime:/etc/localtime:ro     
    ports:                                   
      - "3000:3000"                          
                                             
    # see https://blog.ssdnodes.com/blog/using-docker-compose-self-hosting/               
volumes:                                     
 certs:                                      
 vhost.d:                                    
 html:
                               
networks:                                    
 proxy-tier:
```
