### ISSUE TITLE
docker run wettyoss/wetty fails with login[47] error

### ISSUE THREAD

**Issue by PurnaChandraPanda** [butlerx/wetty#464]
From ubuntu terminal, run:
```
$ docker pull wettyoss/wetty:latest
$ docker run -it -p 3002:3000 wettyoss/wetty:latest --shh-user=user1 --ssh-pass=mypwd
```

On browser, access the app as http://localhost:3002/wetty.
Provided the correct username and password values, but still fails as "Login incorrect".
```
28c1d1d02bcf login: user1
Password: 
Login incorrect
28c1d1d02bcf login: 
```

On the other `docker run` session, I could see it flags as `login[47]` error with invalid password for unknown.
```
{"label":"Wetty","level":"info","message":"Connection accepted.","timestamp":"2023-03-10T05:03:28.331Z"}
{"address":"localhost","label":"Wetty","level":"info","message":"Process Started on behalf of user","pid":47,"timestamp":"2023-03-10T05:03:28.345Z"}
login[47]: invalid password for 'UNKNOWN' on 'pts/1' from 'localhost'
```

I could validate in ubuntu terminal that username and password are correct values, but /wetty terminal does not accept it. How else could we validate from "wetty", why the user/pwd combination is declined? Could anyone please share some thoughts??

**Comment by PurnaChandraPanda** [comment]
@butlerx Any thoughts on this login challenge?

**Comment by PurnaChandraPanda** [comment]
any comments how to address it?

**Comment by Aledangelo** [comment]
I have same issue. Do you know if there are default credentials to use?

**Comment by inceabdullah** [comment]
Please pass host users into the container like
```bash
docker run -v /etc/passwd:/etc/passwd -u `id -u`:`id -g` -v `pwd`:`pwd`  -it --rm --net host --name wetty wettyoss/wetty  
```


----
For other `running as a host user within a Docker` methods: [Ref](https://stackoverflow.com/questions/45836272/running-as-a-host-user-within-a-docker-container/45959754)

**Comment by eded333** [comment]
A bit of necromancy...
This is my docker compose deployment that worked for me:

```
services:
  wetty:
    image: wettyoss/wetty:latest
    container_name: wetty
    environment:
      - PUID=1000
      - PGID=1000
    user: 1000:1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    network_mode: host
    restart: unless-stopped
```
