### ISSUE TITLE
Documentation of Environment Variables and Help With Docker Compose Please!

### ISSUE THREAD

**Issue by JohnHind** [butlerx/wetty#521]
This looks like very useful software, but can anyone help me with setting it up please!

What I want to achieve: I want a docker container running on a Raspberry Pi which will serve me a terminal in a remote browser onto the host operating system which is running the docker container.

What already works: I can get a remote SSH terminal (for example from VS Code) on 'pi@octosnap.local' with a known password.

What I have tried: After a lot of research and faffing about I determined that the following Docker Compose ought to work:
```
version:  "3"
services:
  wetty:
    image: wettyoss/wetty:latest
    container_name: wetty
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REMOTE_SSH_SERVER=host.docker.internal
    ports:
      - 3002:3000
    restart: unless-stopped
```
But when I point my remote browser at "http://octosnap.local:3002/wetty", I get the following:
```
0336df9ce175 login: pi
Password: 
Login incorrect
0336df9ce175 login: 
```
Ping host.docker.internal from a terminal within the Docker container works fine. I was also able to ssh pi@host.docker.internal from within the container although it did prompt me to accept the key fingerprint, but gave the correct pi@octosnap: command prompt.

Is it trying to connect to the wrong server? What does the hex string ahead of 'login' mean? Is the environment variable supported? I can find no documentation of environment variables here, but did find several sources for this around the Internet. If not, how can I pass the host address into the Docker container? Am I missing something else?

Help!

**Comment by Luigi600** [comment]
> Is the environment variable supported? I can find no documentation of environment variables here

Clear and unequivocal: no.

As you can see from the README, the values are passed as [program arguments](https://github.com/butlerx/wetty/blob/v2.7.0/README.md?plain=1#L89). Therefore, you must use the arguments in your Docker Compose file instead of environment variables. The key word here is [`command`](https://docs.docker.com/compose/compose-file/compose-file-v3/#command). In your case, the file should look like this:

```yaml
version:  "3"
services:
  wetty:
    image: wettyoss/wetty:latest
    container_name: wetty
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - "--ssh-host"
      - "host.docker.internal"
    ports:
      - 3002:3000
    restart: unless-stopped
```

For example, `--ssh-user' and others can now be set in the same schema.
